/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Modify.loginmodify;
import javax.swing.JOptionPane;

/**
 *
 * @author This PC
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAccount = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();
        BGR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAccount.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtAccount.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), null));
        txtAccount.setOpaque(false);
        getContentPane().add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 352, 260, 30));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), null));
        txtPassword.setOpaque(false);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 462, 260, 30));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Loginicon.png"))); // NOI18N
        Login.setText("Đăng Nhập");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 130, 30));

        SignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Umar123-Mantra-Cloud-Upload-On.32.png"))); // NOI18N
        SignUp.setText("Đăng Ký");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 130, 30));

        BGR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/LoginBGR.png"))); // NOI18N
        getContentPane().add(BGR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String account = txtAccount.getText();
        String password = txtPassword.getText();
        if(password.length()==0 || account.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Please check your input","Input Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(loginmodify.CheckLog(account,password)==true)
            {
                JOptionPane.showMessageDialog(null,"Login Successfully");
                QLyPhimFrame a = new QLyPhimFrame();
                a.setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Login Error","Error",JOptionPane.ERROR_MESSAGE);
                txtAccount.setText("");
                txtPassword.setText("");
            }
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        dispose();
        SignUpFrame a = new SignUpFrame();
        a.setVisible(true);
    }//GEN-LAST:event_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGR;
    private javax.swing.JButton Login;
    private javax.swing.JButton SignUp;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
